import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/shared/components/Navbar";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import Footer from "@/shared/components/Footer";
import { Toaster } from "sonner";
import ProgressProviders from "@/shared/components/ProgressProvider";
import { AuthProvider } from "@/shared/components/AuthProvider";

const notoSansHeading = Noto_Sans({ subsets: ['latin'], variable: '--font-heading' });

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-mono", jetbrainsMono.variable, notoSansHeading.variable)}
    >
      <body className="bg-[linear-gradient(90deg,_rgba(26,26,29,1)_0%,_rgba(46,7,63,1)_44%,_rgba(26,26,29,1)_100%)] min-h-full">
        <AuthProvider>
          <ProgressProviders>
            <NuqsAdapter>
              <Navbar />
              <Toaster />
              {children}
              <Footer />
            </NuqsAdapter>
          </ProgressProviders>
        </AuthProvider>
      </body>
    </html>
  );
}
